```{r}
#Load libraries
library(tidyverse)
library(pals)
## library(ggtree)
library(ape)
library(adephylo)
library(Seurat)

library(ggplot2)
library(ggdendro)
library(cowplot)
library(phylogram)
library(dendextend)
library(circlize)
library(RColorBrewer)
library(viridis)
#library(ggsci)
library(pvclust)
#library(reshape2)
#library(stats)
```


```{r}
#Figure 3a 
ph <- NormalizeData(ph)
ph <- FindVariableFeatures(ph, nfeatures = 2000)
ph <- ScaleData(ph)
ph <- RunPCA(ph)
ph <- RunUMAP(ph, dims = 1:50)

ph <- FindNeighbors(ph, dims = 1:10)
ph <- FindClusters(ph, resolution = 0.5)
##PRs (No Integration)
DimPlot(ph, group.by = "species")

##PRs (Integrated)
DimPlot(OrthoObject2, group.by = "species")
```

```{r}
# Figure 3b - Marker Gene Feature Plots
FeaturePlot(OrthoObject2, features = "RHO")
FeaturePlot(OrthoObject2, features = c("THRB"))
FeaturePlot(OrthoObject2, features = c("OPN1SW"))
FeaturePlot(OrthoObject2, features = c("CALB1")) #Talk about how CALB1 cannot be applied for other animals and why.

```

```{r}
#Figure 3c - OrthoType Plot
#Merging Seurat Cluster 2 & 3
Idents(OrthoObject2) = "seurat_clusters"
OrthoObject2 <- MergeClusters(OrthoObject2, idents = c(2,3), refactor = TRUE)
#Renaming SeuratClusters to OrthoType identity
OrthoObject2$seurat_clusters <- sub("0", "oLM-cone", OrthoObject2$seurat_clusters)
OrthoObject2$seurat_clusters <- sub("1", "oS-cone", OrthoObject2$seurat_clusters)
OrthoObject2$seurat_clusters <- sub("2", "oRod", OrthoObject2$seurat_clusters)

#Viewing UMAP Plots
DimPlot(OrthoObject2, group.by = "celltype")
DimPlot(OrthoObject2, group.by = "seurat_clusters")
```

```{r}
##3d - Mouse Confusion Matrix
type_table <- table(OrthoObject2@meta.data$species_class, OrthoObject2@meta.data$seurat_clusters)
mouse_table <- type_table[grep("mar", rownames(type_table)),]

species <- c("human", "marmoset", "mouse", "squirrel", "cow", "lizard", "chicken")

species_order <-c("human_rod", "human_l/m-cone","human_s-cone","marmoset_rod", "marmoset_l/m-cone","marmoset_s-cone", "mouse_rod", "mouse_l/m-cone","mouse_s-cone", "squirrel_rod", "squirrel_l/m-cone","squirrel_s-cone","cow_rod", "cow_l/m-cone","cow_s-cone","lizard_rod", "lizard_l/m-cone","lizard_s-cone","chicken_rod", "chicken_l/m-cone","chicken_s-cone", "chicken_double-cone")
OT_order <- c("oRod","oLM-cone", "oS-cone")

plotConfusionMatrix(mouse_table[species_order, OT_order], col.high = "darkblue", col.low = "white", xlab.use = "OT", ylab.use = "Mouse Types")

mouse_table = t(scale(t(mouse_table), center = FALSE, scale = rowSums(mouse_table)))*103
df = melt(mouse_table)
colnames(df) = c("Mouse_Type", "OT", "mapping")
df$Mouse_Type = factor(df$Mouse_Type, levels = species_order)
df$OT = factor(df$OT, levels = rev(OT_order))

#For first species
ggplot(data = df, aes(x = Mouse_Type, y = OT, fill = mapping)) +
  geom_tile(colour = "gray50", size = 0.2) +
  guides(fill = guide_legend(title = "Mapping %")) +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis labels
    axis.title.x = element_blank(),  # Remove x-axis title
    panel.background = element_blank(),  # Remove panel background
    panel.border = element_blank(),
    plot.margin = margin(l = 7.5, r = 7.5)  # Adjust plot margins for a skinnier graph
  ) +
  scale_fill_gradientn(colors = c("#FFFFFF", "#DFE6FF", "#7292FF", "#002DC6", "#002191"), na.value = "gray70") +
  scale_y_discrete(limits = levels(df$OT)) 



```


```{r}
#Figure 3e - OrthoType DE genes
Idents(OrthoObject2) = "seurat_clusters"
rod_markers_OT <- FindMarkers(OrthoObject2, ident.1 = "oRod", ident.2 = NULL, only.pos = TRUE)
head(rod_markers_OT, n = 7)
scone_markers_OT <- FindMarkers(OrthoObject2, ident.1 = "oS-cone", ident.2 = NULL, only.pos = TRUE)
head(scone_markers_OT, n = 8)
lmcone_markers_OT <- FindMarkers(OrthoObject2, ident.1 = "oLM-cone", ident.2 = NULL, only.pos = TRUE)
head(lmcone_markers_OT, n = 7)

markers = c("OPN1SW", "CCDC136", "AGAP1","RHO", "GNAT1", "SAG",  "PDE6C", "THRB", "CNGB3")

DotPlot(OrthoObject2, features = markers, assay = "RNA", group.by = "seurat_clusters", cols = c("white", "#6e78ff")) + RotatedAxis()
dev.off()
```

```{r}
#Figure 3f

type_table <- table(OrthoObject2@meta.data$species_class, OrthoObject2@meta.data$seurat_clusters)
type_table = type_table[rowSums(type_table) > 20,]
max_type <- colnames(type_table)[max.col(type_table)]

types_plot <- which(max_type == "oRod")
types_plot <- c(types_plot, which(max_type == "oS-cone"))
types_plot <- rownames(type_table)[types_plot]

OT_order <- c("oLM-cone, oS-cone, oRod")
plot_table <- type_table[types_plot, OT_order]

plot_table = t(scale(t(plot_table), center = FALSE, scale = rowSums(plot_table))) * 100
df = melt(plot_table)

colnames(df) = c("species", "OT", "mapping")
df$species = factor(df$species, levels = rev(types_plot))
df$seurat_clusters = factor(df$seurat_clusters, levels = OT_order)


```

```{r}
#Updated Figure 3f
#Merging Seurat Cluster 2 & 3
Idents(OrthoObject_Fig3) = "seurat_clusters"
#Renaming some of the cell-types
OrthoObject_Fig3$celltype <- sub("Rod", "rod", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("ML_cone", "l/m-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("MW_cone", "l/m-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("S_cone", "s-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("mlCone", "l/m-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("SCone", "s-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("sCones", "s-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("l/m-cones", "l/m-cone", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("rods", "rod", OrthoObject_Fig3$celltype)
OrthoObject_Fig3$celltype <- sub("double", "double-cone", OrthoObject_Fig3$celltype)

#OrthoObject_Fig3 <- MergeClusters(OrthoObject_Fig3, idents = c(2,3), refactor = TRUE)
#Renaming SeuratClusters to OrthoType identity
OrthoObject_Fig3$seurat_clusters <- sub("0", "oLM-cone", OrthoObject_Fig3$seurat_clusters)
OrthoObject_Fig3$seurat_clusters <- sub("1", "oS-cone", OrthoObject_Fig3$seurat_clusters)
OrthoObject_Fig3$seurat_clusters <- sub("2", "oRod", OrthoObject_Fig3$seurat_clusters)
#Cow_0, #Human0, Marmoset2, Mouse_rod, Squirrel_4, Lizard_11, Chicken1

type_table <- table(OrthoObject_Fig3@meta.data$seuratcluster_species, OrthoObject_Fig3@meta.data$seurat_clusters)
type_table <- type_table[seuratcluster_species_order,]
type_table = type_table[rowSums(type_table) > 20,]
max_type <- colnames(type_table)[max.col(type_table)]


types_plot <- which(max_type == "oRod")
types_plot <- c(types_plot, which(max_type == "oS-cone"))
types_plot <- rownames(type_table)[types_plot]

OT_order <- c("oLM-cone", "oRod", "oS-cone")
seuratcluster_species_order <- c("chicken_1", "cow_0","human_1","lizard_11","marmoset_2", "mouse_rod", "squirrel_4", "chicken_7", "lizard_8", "cow_5", "squirrel_3", "mouse_s-cone", "marmoset_5", "human_19")

plot_table <- type_table[types_plot, OT_order]

plot_table = t(scale(t(plot_table), center = FALSE, scale = rowSums(plot_table))) * 100
df = melt(plot_table)
colnames(df) = c("Species_Type", "OT", "mapping")
df$Species_Type = factor(df$Species_Type, levels = rev(types_plot))
df$OT = factor(df$OT, levels = OT_order)


ggplot(data = df, aes(x=OT, y=Species_Type, fill=mapping)) +
    geom_tile(colour="gray50", size=0.2) +
  guides(fill=guide_legend(title="Mapping %")) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 1),
          panel.border = element_blank(),
          axis.title = element_blank()) +
    scale_fill_gradient(low = "white",  high = "#A31C0A", na.value = "gray70") + scale_x_discrete(limits = levels(df$OT)) +coord_flip()
dev.off()
```



