#Scaling Data
```{r}
#data <- LoadH5Seurat("/Users/vishruthdinesh/Downloads/Ind_Seurat_Objects/CleanIntegratedObject.h5seurat")
OrthoObject4 <- data
OrthoObject4 = ScaleData(OrthoObject4, features = rownames(OrthoObject4))
DefaultAssay(OrthoObject4) = "RNA"
OrthoObject4$seurat_clusters <- sub("oS-cone", "oCone", OrthoObject4$seurat_clusters)
OrthoObject4$seurat_clusters <- sub("oLM-cone", "oCone", OrthoObject4$seurat_clusters)
OrthoObject4$celltype <- sub("s-cone", "Cone", OrthoObject4$celltype)
OrthoObject4$celltype <- sub("l/m-cone", "Cone", OrthoObject4$celltype)
OrthoObject4$celltype <- sub("double-cone", "Cone", OrthoObject4$celltype)
OrthoObject4$celltype <- sub("rod", "Rod", OrthoObject4$celltype)
#Idents(OrthoObject4) = "celltype"
#OrthoObject4 = subset(OrthoObject4, cells = WhichCells(OrthoObject4, downsample = 300, seed = 12345))
OrthoObject4$dendro.order = factor(OrthoObject4$celltype)
table(OrthoObject4$dendro.order)

```

#Dividing Into Phylogenetic Clades + Markers
```{r}
logFC.threshold = 0.5
padj.threshold = 0.05

library(presto)

# Primate DEGs
PrimatePR = subset(OrthoObject4, species %in% c("marmoset", "human"))

PrimatePRMarkers = wilcoxauc(PrimatePR, 'celltype')
#genes_human = rownames(human_ortho)
#genes_marmoset = rownames(marmoset_ortho)
#common_primate_genes <- intersect(genes_human, genes_marmoset)
#PrimatePR = PrimatePR[common_primate_genes,]
#PrimatePRMarkers = wilcoxauc(PrimatePR, 'celltype')

# Rodent DEGs
#RodentPR <- subset(OrthoObject4, species %in% c("mouse", "squirrel"))
RodentPR <- subset(OrthoObject4, species %in% c("mouse", "squirrel"))
RodentPRMarkers = wilcoxauc(RodentPR, 'celltype')

# Laurasiatherian DEGs
LaurasiaPR = subset(OrthoObject4, species %in% c("cow"))
LaurasiaPRMarkers = wilcoxauc(LaurasiaPR, 'celltype')

#Lizard+Chicken
LizChickPR = subset(OrthoObject4, species %in% c("lizard", "chicken"))
LizChickPRMarkers = wilcoxauc(LizChickPR, 'celltype')
```
# Extract top genes
```{r}
library("dplyr")
Primate_Cone_subset = subset(PrimatePRMarkers, group == "Cone" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
Primate_Rod_subset = subset(PrimatePRMarkers, group == "Rod" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)

PrimateDEGs <- rbind(Primate_Cone_subset, Primate_Rod_subset)


Rodent_Cone_subset = subset(RodentPRMarkers, group == "Cone" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
Rodent_Cone_subset1 = subset(RodentPRMarkers, group == "Cone" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)%>% 
  head(75)
Rodent_Rod_subset = subset(RodentPRMarkers, group == "Rod" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
RodentDEGs <- rbind(Rodent_Cone_subset, Rodent_Rod_subset)
RodentDEGs_Vis <- rbind(Rodent_Cone_subset1, Rodent_Rod_subset)



Laurasia_Cone_subset1 = subset(LaurasiaPRMarkers, group == "Cone" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)%>% head(100)
Laurasia_Cone_subset = subset(LaurasiaPRMarkers, group == "Cone" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
Laurasia_Rod_subset = subset(LaurasiaPRMarkers, group == "Rod" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
LaurasiaDEGs <- rbind(Laurasia_Cone_subset,  Laurasia_Rod_subset)
LaurasiaDEGs_Vis <- rbind(Laurasia_Cone_subset1,  Laurasia_Rod_subset)

#LizChick_Cone_subset = subset(LizChickPRMarkers, group == "oCone" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
#LizChick_Rod = subset(LizChickPRMarkers, group == "oRod" & logFC > logFC.threshold & padj < padj.threshold) %>% arrange(padj)
#LizChickDEGs <- rbind(LizChick_LM_subset, LizChick_S_subset, LizChick_Rod)

# Conserved and species-enriched genes
# Flatten the lists into vectors
PrimateDEGs_flat <- unlist(PrimateDEGs)
RodentDEGs_flat <- unlist(RodentDEGs)
LaurasiaDEGs_flat <- unlist(LaurasiaDEGs)
#LizChickDEGs_flat <- unlist(LizChickDEGs)

# Combine the vectors into a list
shared <- list(PrimateDEGs_flat, RodentDEGs_flat, LaurasiaDEGs_flat)

# Perform intersection on the flattened vectors
sharedDEGs <- Reduce(intersect, shared)


primateSpecificDEGs = lapply(seq_along((levels(OrthoObject4$dendro.order))), function(element){
  speciesDEGs = PrimateDEGs$feature
  return(speciesDEGs[!speciesDEGs %in% c(RodentDEGs_Vis$feature, LaurasiaDEGs_Vis$feature)])
  })
primateSpecificDEGs = primateSpecificDEGs[[1]]

rodentSpecificDEGs = lapply(seq_along((levels(OrthoObject4$dendro.order))), function(element){
  speciesDEGs = RodentDEGs_Vis$feature
  return(speciesDEGs[!speciesDEGs %in% c(PrimateDEGs$feature, LaurasiaDEGs_Vis$feature)])
  })
rodentSpecificDEGs = rodentSpecificDEGs[[1]]

laurasiaSpecificDEGs = lapply(seq_along((levels(OrthoObject4$dendro.order))), function(element){
  speciesDEGs = LaurasiaDEGs_Vis$feature
  return(speciesDEGs[!speciesDEGs %in% c(RodentDEGs_Vis$feature, PrimateDEGs$feature)])
  })
laurasiaSpecificDEGs = laurasiaSpecificDEGs[[1]]

```

```{r}
message("# of shared genes found: ", length(unique(sharedDEGs %>% unlist)))
message("# of shared genes found: ", length(unique(primateSpecificDEGs %>% unlist)))
message("# of shared genes found: ", length(unique(rodentSpecificDEGs %>% unlist)))
message("# of shared genes found: ", length(unique(laurasiaSpecificDEGs %>% unlist)))
```


```{r}
library(ggplot2)
library('cowplot')
#new_order <- c("oCone", "oRod")
#OrthoObject4$dendro.order <- factor(OrthoObject4$seurat_clusters)
PrimateSubset = subset(PrimatePR, cells = WhichCells(PrimatePR, downsample = 100, seed = 12345))
RodentSubset = subset(RodentPR, cells = WhichCells(RodentPR, downsample = 100, seed = 12345))
RodentSubset = ScaleData(RodentPR, features = rownames(RodentPR))
LaurasiaSubset = subset(LaurasiaPR, cells = WhichCells(LaurasiaPR, downsample = 100, seed = 12345))

panel1 = ConservedEnrichedHeatmap(PrimateSubset, sharedDEGs, primateSpecificDEGs, rodentSpecificDEGs, laurasiaSpecificDEGs,
                                  group.by = "dendro.order", group.bar = FALSE,  draw.lines = FALSE)
panel2 = ConservedEnrichedHeatmap(RodentSubset, sharedDEGs, primateSpecificDEGs, rodentSpecificDEGs, laurasiaSpecificDEGs,
                                  group.by = "dendro.order", group.bar = FALSE,  draw.lines = FALSE)
panel3 = ConservedEnrichedHeatmap(LaurasiaSubset, sharedDEGs, primateSpecificDEGs, rodentSpecificDEGs, laurasiaSpecificDEGs,
                                  group.by = "dendro.order", group.bar = FALSE,  draw.lines = FALSE)

full_panel =  plot_grid(panel1, 
                        panel2, 
                        panel3, 
                        nrow = 3)

full_panel

```

```{r}
panel1 = ConservedEnrichedHeatmap2(PrimateSubset, RodentSubset, LaurasiaSubset, sharedDEGs,
                                   group.by = "dendro.order", group.bar = FALSE, draw.lines = FALSE, color = "magenta")
panel2 = ConservedEnrichedHeatmap2(PrimateSubset, RodentSubset, LaurasiaSubset, primateSpecificDEGs,
                                   group.by = "dendro.order", group.bar = FALSE, draw.lines = FALSE, color = "blue")
panel3 = ConservedEnrichedHeatmap2(PrimateSubset, RodentSubset, LaurasiaSubset, rodentSpecificDEGs,
                                   group.by = "dendro.order", group.bar = FALSE, draw.lines = FALSE, color = "turquoise3")
panel4 = ConservedEnrichedHeatmap2(PrimateSubset, RodentSubset, LaurasiaSubset, laurasiaSpecificDEGs,
                                   group.by = "dendro.order", group.bar = FALSE, draw.lines = FALSE, color = "orange")

full_panel =  plot_grid(panel1,
                        panel2,
                        panel3,
                        panel4,
                        nrow = 4)

full_panel
```

##Figure 4B - Venn Diagrams
```{r}
# Split PrimateDEGs based on cell types 
library(VennDiagram)
library(eulerr)

primate_rod_genes <- PrimateDEGs[PrimateDEGs$group == "Rod", "feature"]
primate_cone_genes <- PrimateDEGs[PrimateDEGs$group == "Cone", "feature"]
rodent_rod_genes <- RodentDEGs[RodentDEGs$group == "Rod", "feature"]
rodent_cone_genes <- RodentDEGs[RodentDEGs$group == "Cone", "feature"]
laurasia_rod_genes <- LaurasiaDEGs[LaurasiaDEGs$group == "Rod", "feature"]
laurasia_cone_genes <- LaurasiaDEGs[LaurasiaDEGs$group == "Cone", "feature"]

myCol <- c("blue","turquoise","orange")

# Create Venn diagrams for each cell type
venn_rod <- venn.diagram(
  x = list(Primate = primate_rod_genes, Rodent = rodent_rod_genes, Laurasia = laurasia_rod_genes),
  category.names = c("Primate", "Rodent", "Laurasia"),
  filename = NULL,
  output = TRUE
)

venn_cone <- venn.diagram(
  x = list(Primate = primate_cone_genes, Rodent = rodent_cone_genes, Laurasia = laurasia_cone_genes),
  filename = NULL,
  fill = c("#1235FA", '#C80D92', '#EA8A24'))

# Display Venn diagram
grid.draw(venn_cone)

#Customization of VennDiagram: Circle Area Proportional to Number of DEGs
vennd_cone <- euler(c(A = 72, B = 167, "A&B" = 14, C = 149, 
                "A&C" = 29, "B&C" = 32, "A&B&C" = 18))
plot(vennd_cone, fills = c("blue", "turquoise", "orange"), quantities = TRUE)

vennd_rod <- euler(c(A = 64, B = 26, "A&B" = 6, C = 33, 
                "A&C" = 4, "B&C" = 3, "A&B&C" = 8))
plot(vennd_rod, fills = c("blue", "turquoise", "orange"), quantities = TRUE)



```
##Figure 4C - Gene Ontology
```{r}
library(clusterProfiler)
library(org.Hs.eg.db)

rodentSpecificDEGs = lapply(seq_along((levels(OrthoObject4$dendro.order))), function(element){
  speciesDEGs = RodentDEGs$feature
  return(speciesDEGs[!speciesDEGs %in% c(PrimateDEGs$feature, LaurasiaDEGs$feature)])
  })
rodentSpecificDEGs = rodentSpecificDEGs[[1]]

laurasiaSpecificDEGs = lapply(seq_along((levels(OrthoObject4$dendro.order))), function(element){
  speciesDEGs = LaurasiaDEGs$feature
  return(speciesDEGs[!speciesDEGs %in% c(RodentDEGs$feature, PrimateDEGs$feature)])
  })
laurasiaSpecificDEGs = laurasiaSpecificDEGs[[1]]

geneLists = lapply(list(sharedDEGs, PrimateDEGs$feature, RodentDEGs$feature, LaurasiaDEGs$feature), function(x) sort(unique(unlist(x))))
names(geneLists) = c("shared", "primates", "rodents", "laurasia")

GO.results = lapply(geneLists, function(geneList){
  enrichGO(gene = geneList,
                # universe      = names(geneList),
                OrgDb         = org.Hs.eg.db,
                keyType       = 'SYMBOL',
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE)
})
```

```{r}
library(ggplot2)
GO.plots = lapply(GO.results, function(ego) dotplot(ego, showCategory=10) + scale_fill_gradient(low = "magenta", high = "turquoise"))

#ggarrange(plotlist = GO.plots, nrow = 2, ncol =2, labels = names(geneLists), hjust = 0, align = "v")
shared_plot = GO.plots$shared
primate_plot = GO.plots$primates
rodent_plot = GO.plots$rodents
laurasia_plot = GO.plots$laurasia

shared_plot
primate_plot
rodent_plot
laurasia_plot
```


#Figure 4D Preparation
```{r}

#Loading Required Packages
library(org.Hs.eg.db)
hs <- org.Hs.eg.db

PrimateDEGs_feature = PrimateDEGs$feature
RodentDEGs_feature = RodentDEGs$feature
LaurasiaDEGs_feature = LaurasiaDEGs$feature

#Convert Gene Symbols to Entrez Gene
my.symbols <- sharedDEGs
my.symbols_2 <- PrimateDEGs_feature
my.symbols_3 <- RodentDEGs_feature
my.symbols_4 <- LaurasiaDEGs_feature

EntrezGeneID_shared = select(hs, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "SYMBOL")
EntrezGeneID_shared = EntrezGeneID_shared$ENTREZID


EntrezGeneID_primate = select(hs, 
       keys = my.symbols_2,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "SYMBOL")
EntrezGeneID_primate = EntrezGeneID_primate$ENTREZID


EntrezGeneID_rodent = select(hs, 
       keys = my.symbols_3,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "SYMBOL")
EntrezGeneID_rodent = EntrezGeneID_rodent$ENTREZID


EntrezGeneID_laurasia = select(hs, 
       keys = my.symbols_4,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "SYMBOL")
EntrezGeneID_laurasia = EntrezGeneID_laurasia$ENTREZID

#DO package
library(DOSE)


gene_shared <- EntrezGeneID_shared
gene_primate <- EntrezGeneID_primate
gene_rodent <- EntrezGeneID_rodent
gene_laurasia <- EntrezGeneID_laurasia

#Running Disease Ontology algorithm
x_shared <- enrichDO(gene = gene_shared,
              ont           = "DO",
              pvalueCutoff  = 0.05,
              pAdjustMethod = "BH",
              minGSSize     = 5,
              maxGSSize     = 500,
              qvalueCutoff  = 0.05,
              readable      = FALSE)

x_primate <- enrichDO(gene = gene_primate,
              ont           = "DO",
              pvalueCutoff  = 0.05,
              pAdjustMethod = "BH",
              minGSSize     = 5,
              maxGSSize     = 500,
              qvalueCutoff  = 0.05,
              readable      = FALSE)

x_rodent <- enrichDO(gene = gene_rodent,
              ont           = "DO",
              pvalueCutoff  = 0.05,
              pAdjustMethod = "BH",
              minGSSize     = 5,
              maxGSSize     = 500,
              qvalueCutoff  = 0.05,
              readable      = FALSE)

x_laurasia <- enrichDO(gene = gene_laurasia,
              ont           = "DO",
              pvalueCutoff  = 0.05,
              pAdjustMethod = "BH",
              minGSSize     = 5,
              maxGSSize     = 500,
              qvalueCutoff  = 0.05,
              readable      = FALSE)


```
##Figure 4D - Disease Ontology
```{r}
#Bar Plot
mutate(x_shared, qscore = -log(p.adjust, base=10)) %>% 
    barplot(x="qscore")
mutate(x_primate, qscore = -log(p.adjust, base=10)) %>% 
    barplot(x="qscore")


#DotPlot
library(enrichplot)
dotplot(x_shared, showCategory=30) + ggtitle("Shared")+ scale_fill_gradient(low = "magenta", high = "turquoise")
dotplot(x_primate, showCategory=30) + ggtitle("Primate")+ scale_fill_gradient(low = "magenta", high = "turquoise")
```




##Figure 4E - Further Explorations with DO
```{r}
#Gene-Concept Network
edox_shared <- setReadable(x_shared, 'org.Hs.eg.db', 'ENTREZID')
edox_primate <- setReadable(x_primate, 'org.Hs.eg.db', 'ENTREZID')

p2 <- cnetplot(edox_primate, foldChange=PrimateDEGs$feature)
p1 <- cnetplot(edox_shared, foldChange=sharedDEGs)
cowplot::plot_grid(p1,p2, ncol=2, labels=LETTERS[1:3], rel_widths=c(.8, .8, 1.2))


p2 <- heatplot(edox, foldChange=geneList, showCategory=5)

xx <- compareCluster(sharedDEGs, fun="enrichKEGG",
                  pvalueCutoff=0.05)
xx <- pairwise_termsim(xx)                     
p1 <- emapplot(xx)
```



