```{r}
#Load libraries
library(tidyverse)
library(pals)
## library(ggtree)
library(ape)
library(adephylo)
library(Seurat)

library(ggplot2)
library(ggdendro)
library(cowplot)
library(phylogram)
library(dendextend)
library(circlize)
library(RColorBrewer)
library(viridis)
#library(ggsci)
#library(pvclust)
#library(reshape2)
#library(stats)
```


```{r}
#Figure 3a 
ph_ortho <- NormalizeData(ph_ortho)
ph_ortho <- FindVariableFeatures(ph_ortho, nfeatures = 2000)
ph_ortho <- ScaleData(ph_ortho)
ph_ortho <- RunPCA(ph_ortho)
ph_ortho <- RunUMAP(ph_ortho, dims = 1:50)

ph_ortho <- FindNeighbors(ph_ortho, dims = 1:10)
ph_ortho <- FindClusters(ph_ortho, resolution = 0.5)
DimPlot(ph_ortho, group.by = "species")+NoLegend() + NoAxes() +labs(title = NULL)
ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3a_unintegrated.pdf", width = 7.5, height = 5)
##PRs (No Integration)

##PRs (Integrated)
DimPlot(OrthoObject2, group.by = "species")+NoLegend() + NoAxes() +labs(title = NULL)
ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3a_integrated.pdf", width = 7.5, height = 5)
```

```{r}
# Figure 3b - Marker Gene Feature Plots
#data <- LoadH5Seurat("/Users/vishruthdinesh/Downloads/Ind_Seurat_Objects/CleanIntegratedObject.h5seurat")
OrthoObject2 <- data

FeaturePlot(OrthoObject2, features = "RHO") + NoAxes() +labs(title = NULL)
FeaturePlot(OrthoObject2, features = c("THRB"))+NoLegend() + NoAxes() +labs(title = NULL)
FeaturePlot(OrthoObject2, features = c("OPN1SW"))+NoLegend() + NoAxes() +labs(title = NULL)
FeaturePlot(OrthoObject2, features = c("CALB1"))+NoLegend() + NoAxes() +labs(title = NULL) #Talk about how CALB1 cannot be applied for other animals and why.


ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3b_legend.pdf", width = 7.5, height = 5)
```

```{r}
#Figure 3c - OrthoType Plot
#Merging Seurat Cluster 2 & 3
Idents(OrthoObject2) = "seurat_clusters"
#OrthoObject2 <- MergeClusters(OrthoObject2, idents = c(2,3), refactor = TRUE)
#Renaming SeuratClusters to OrthoType identity
#OrthoObject2$seurat_clusters <- sub("0", "oLM-cone", OrthoObject2$seurat_clusters)
#OrthoObject2$seurat_clusters <- sub("1", "oS-cone", OrthoObject2$seurat_clusters)
#OrthoObject2$seurat_clusters <- sub("2", "oRod", OrthoObject2$seurat_clusters)

#Viewing UMAP Plots
p <- DimPlot(OrthoObject2, group.by = "seurat_clusters")+NoLegend() + NoAxes() +labs(title = NULL)
plot(p)
ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3c.pdf", width = 7.5, height = 5)

```

```{r}
##3d - Mouse Confusion Matrix
OrthoObject2@meta.data$species_class <- paste0(OrthoObject2@meta.data$species, "_", OrthoObject2@meta.data$celltype)
type_table <- table(OrthoObject2@meta.data$species_class, OrthoObject2@meta.data$seurat_clusters)
mouse_table <- type_table

species <- c("human", "marmoset", "mouse", "squirrel", "cow", "lizard", "chicken")

species_order <-c("human_rod", "human_l/m-cone","human_s-cone","marmoset_rod", "marmoset_l/m-cone","marmoset_s-cone", "mouse_rod", "mouse_l/m-cone","mouse_s-cone", "squirrel_rod", "squirrel_l/m-cone","squirrel_s-cone","cow_rod", "cow_l/m-cone","cow_s-cone","lizard_rod", "lizard_l/m-cone","lizard_s-cone","chicken_rod", "chicken_l/m-cone","chicken_s-cone", "chicken_double-cone")
OT_order <- c("oRod","oLM-cone", "oS-cone")

plotConfusionMatrix(type_table[species_order, OT_order], col.high = "darkblue", col.low = "white", xlab.use = "OT", ylab.use = "Mouse Types")

type_table = t(scale(t(type_table), center = FALSE, scale = rowSums(type_table)))*103
df = melt(type_table)
colnames(df) = c("Mouse_Type", "OT", "Mapping")
df$Mouse_Type = factor(df$Mouse_Type, levels = species_order)
df$OT = factor(df$OT, levels = rev(OT_order))

#For first species
ggplot(data = df, aes(x = Mouse_Type, y = OT, fill = Mapping)) +
  geom_tile(colour = "gray50", size = 0.2) +
  #guides(fill = guide_legend(title = "Mapping %")) +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis labels
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),  # Remove y-axis labels
    axis.title.y = element_blank(), # Remove x-axis title
    panel.background = element_blank(),  # Remove panel background
    panel.border = element_blank(),
   #legend.position = "none",
    plot.margin = margin(l = 7.5, r = 7.5)  # Adjust plot margins for a skinnier graph
  ) +
  scale_fill_gradientn(colors = c("#FFFFFF", "#DFE6FF", "#7292FF", "#002DC6", "#002191"), na.value = "gray70") +
  scale_y_discrete(limits = levels(df$OT)) 

ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3d_withlegend.pdf", width = 10, height = 5)

```


```{r}
#Figure 3e - OrthoType DE genes
Idents(OrthoObject2) = "seurat_clusters"
rod_markers_OT <- FindMarkers(OrthoObject2, ident.1 = "oRod", ident.2 = NULL, only.pos = TRUE)
head(rod_markers_OT, n = 7)
scone_markers_OT <- FindMarkers(OrthoObject2, ident.1 = "oS-cone", ident.2 = NULL, only.pos = TRUE)
head(scone_markers_OT, n = 8)
lmcone_markers_OT <- FindMarkers(OrthoObject2, ident.1 = "oLM-cone", ident.2 = NULL, only.pos = TRUE)
head(lmcone_markers_OT, n = 7)

markers = c("RHO", "GNAT1", "SAG", "PDE6C", "THRB", "CNGB3", "OPN1SW", "CCDC136", "AGAP1")

OrthoObject2$seurat_clusters <- factor(OrthoObject2$seurat_clusters, levels = c(  "oS-cone","oLM-cone","oRod"))
DotPlot(OrthoObject2, features = markers, assay = "RNA", group.by = "seurat_clusters", cols = c("white", "#6e78ff")) + RotatedAxis()+theme(axis.title.y = element_blank())
ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3e.pdf", width = 10, height = 5)
```

```{r}
#Updated Figure 3f

#OrthoObject_Fig3 <- OrthoObject2
OrthoObject_Fig3 <- OrthoObject2

colors = c("#FFFFFF", "#E3E9FF", "#5177FF", "#002DC6", "#002191")
Idents(OrthoObject_Fig3) = "seurat_clusters"


type_table <- table(OrthoObject_Fig3@meta.data$seuratcluster_species, OrthoObject_Fig3@meta.data$seurat_clusters)
#type_table <- type_table[seuratcluster_species_order,]
#type_table = type_table[rowSums(type_table) > 20,]
max_type <- colnames(type_table)[max.col(type_table)]



#types_plot <- which(max_type == "oRod")
types_plot <- which(max_type == "oLM-cone")
types_plot <- c(types_plot, which(max_type == "oS-cone"))
types_plot <- rownames(type_table)[types_plot]

OT_order <- c("oS-cone","oLM-cone")
seuratcluster_species_order <- c("human_3", "marmoset_0", "mouse_0", "squirrel_0", "cow_3","lizard_1", "chicken_4","human_2", "marmoset_5", "mouse_1",  "squirrel_3","cow_5", "lizard_8", "chicken_7")

plot_table <- type_table[seuratcluster_species_order, OT_order]

plot_table = t(scale(t(plot_table), center = FALSE, scale = rowSums(plot_table))) * 100
df = melt(plot_table)
colnames(df) = c("Species_Type", "OT", "mapping")
#df$Species_Type = factor(df$Species_Type, levels = rev(types_plot))
#df$OT = factor(df$OT, levels = OT_order)

#Clean Plot (No labels or legend)
ggplot(data = df, aes(x=OT, y=Species_Type, fill=mapping)) +
    geom_tile(colour="gray50", size=0.2) +
  guides(fill=guide_legend(title="Mapping %")) + 
    theme(
          panel.border = element_blank(),
          axis.text.x = element_blank(),  
          axis.title.x = element_blank(),  
          axis.text.y = element_blank(),    
          axis.title.y = element_blank(),
          axis.title = element_blank(),
          panel.background = element_blank()) +
    scale_fill_gradientn(colors = colors, na.value = "gray70") + scale_x_discrete(limits = levels(df$OT))+NoLegend() +coord_flip()
ggsave("/Users/vishruthdinesh/Downloads/Figures/Fig_3/3f.pdf", width = 10, height = 5)
```



